### ISSUE TITLE
Runtime error running demo.py

### ISSUE THREAD

**Issue by thedavematthews** [NVIDIA/FastPhotoStyle#2]
CUDA 9.1.85-1
Ubuntu 16.04.3
Python 2.7.14

paperspace@abcd:~/style/FastPhotoStyle$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 63, in <module>
    stylized_img = p_wct.transform(cont_img, styl_img, cont_seg, styl_seg)
  File "/home/paperspace/style/FastPhotoStyle/photo_wct.py", line 41, in transform
    csF4 = self.__feature_wct(cF4, sF4, cont_seg, styl_seg)
  File "/home/paperspace/style/FastPhotoStyle/photo_wct.py", line 119, in __feature_wct
    tmp_target_feature = self.__wct_core(cont_feat_view, styl_feat_view)
  File "/home/paperspace/style/FastPhotoStyle/photo_wct.py", line 148, in __wct_core
    c_mean = c_mean.unsqueeze(1).expand_as(cont_feat)
  File "/home/paperspace/anaconda3/envs/style/lib/python2.7/site-packages/torch/tensor.py", line 215, in expand_as
    return self.expand(tensor.size())
RuntimeError: the number of sizes provided       must be greater or equal to the number of dimensions in the tensor at /opt/conda/conda-bld/pytorch_1501972792122/work/pytorch-0.1.12/torch/lib/THC/generic/THCTensor.c:299

**Comment by Yijunmaverick** [comment]
@thedavematthews Thanks for your interests.

I actually do not meet this error. I google it and find from [here](https://discuss.pytorch.org/t/error-at-backward-the-number-of-sizes-provided-must-be-greater-or-equal-to-the-number-of-dimensions-in-the-tensor/9203/4) that it may be due to using pytorch 0.2.0 package. Would you have a [check](https://discuss.pytorch.org/t/how-do-i-know-the-current-version-of-pytorch/6754)? I'm using 0.3.1 now.

**Comment by thedavematthews** [comment]
That worked, thank you!

Note that I was on Torch version 0.1.12_1.
Trying to update to the latest using `conda install pytorch torchvision cuda91 -c pytorch` didn't work, it stayed on the old version. 

Updating with pip fixed it:
`pip install http://download.pytorch.org/whl/cu91/torch-0.3.1-cp27-cp27mu-linux_x86_64.whl`
`pip install torchvision`
http://pytorch.org/
